# Generated by Django 2.2.13 on 2021-03-12 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0079_auto_20210311_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviar_email', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Notificar usuário por email?')),
                ('destino_livre', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Permitir envio a qualquer Unidade de Destino?')),
                ('destinos', models.ManyToManyField(blank=True, related_name='destinos_set', to='materia.UnidadeTramitacao', verbose_name='Destinos Permitidos')),
                ('origens', models.ManyToManyField(related_name='origens_set', to='materia.UnidadeTramitacao', verbose_name='Origens Permitidas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo entre Usuário e Unidade de Tramitação',
                'verbose_name_plural': 'Vínculo entre Usuário e Unidade de Tramitação',
            },
        ),
    ]
